### ISSUE TITLE
DEL not considering VAF Input

### ISSUE THREAD

**Issue by jelisavetailic** [adamewing/bamsurgeon#183]
Hi, 

I have created an input for addSV in which there are deletions with different VAFs (0.6, 0.9 etc.). However, in the final VCF all DEL are with VAF 1 meaning that all reads are deleted. Could you elaborate a bit more on how BamSurgeon insert deletions, and how to make it insert DEL with VAF 0.6?

Thank you.

**Comment by adamewing** [comment]
Sure - could you let me know which version you're using (I'd recommend the latest commit on github) and an example of a delection from your mutation input file?

**Comment by jelisavetailic** [comment]
Hi, 

These are the test examples:

**1.**
input mutations:  
chr1	205272063	205297375	DUP 5
chr2	47333665	47337771	DEL 0.6

output VCF:
<img width="1419" alt="first_ex" src="https://user-images.githubusercontent.com/82386099/125086584-0ebab780-e0cc-11eb-8566-0419b4d9604b.png">

**2.**
input mutations: 
chr1	205291301	205296266	DUP	3	0.6555650690707391
chr2	47336616	47337032	DEL	1	0.05978037007937531

output VCF:
<img width="1429" alt="second_ex" src="https://user-images.githubusercontent.com/82386099/125086628-18dcb600-e0cc-11eb-8f9e-381717727175.png">

**3.**
input mutations:
chr1	205291301	205296266	DUP	5
chr2	47336616	47337032	DEL	0

output VCF:
<img width="1420" alt="third_ex" src="https://user-images.githubusercontent.com/82386099/125086681-25f9a500-e0cc-11eb-906a-a82684d6485e.png">

As you can see all VAFs in output files are 1.0. **My goal is to find a way to calculate the number of DUPs (copy numbers) and VAF of deletions in the output file.** If I have DUP 5 in input file, how can I find that information in the output file (except visually inspecting in BAM Viewer).

As for the version, it is 1.0.

Thanks!

**Comment by jelisavetailic** [comment]
I have updated the version to 1.2, however, everything remains the same.

**Comment by adamewing** [comment]
Apologies for the delayed response and apologies for not being clear: I meant grab the latest commit rather than the latest tagged verson which was quite outdated. I've just updated the latest commit to be version "1.3" - since "1.2" there have been quite a few bugfixes including changes to the VCF output so there's a chance the VAF in the VCF output has been corrected (hope so anyway). If it's still reporting VAF=1.0 for everything let me know and hopefully it's an easy fix (will test on my end as well).

**Comment by jelisavetailic** [comment]
Hi, thank you for the reply. I did take the latest commit (with python3), and not latest release, I have mistaken in the last reply. And I am still getting VAF 1.0. anyways. In the final BAM final it is indeed 1.0, and I would like it to be the number I put in VCF. Thank you! Is there maybe some other possibility why it is ignoring the VAF given?
